### ISSUE TITLE
should python fns / vars be in scope for AIPL ops?

### ISSUE THREAD

**Issue by dovinmu** [saulpw/aipl#32]
```
!!python
@defop('test', 0, 0)
def myfun(aipl, v:str) -> str:
    return 'hi'

!format>myfun
hello

!format
{myfun}
!print
```
Result:
`<function myfun at 0x105d08540>`

I think I'd say probably yes, though I'd think that maybe `myfun` should be overwritten by the !format

**Comment by dovinmu** [comment]
I discovered this when I realized that my @ defop function names were preventing me from writing to an AIPL column with the same name. Not sure I'd ever want those function names to be in scope for AIPL, because I just want the op command.

**Comment by anjakefala** [comment]
In the initial case `!!` put it in the global scope, which I believe [takes priority over the table-scope](https://github.com/saulpw/aipl/blob/67addaa56e6a1cda6d23e163fe09db91c70dbdd2/aipl/ops/format.py#L8). Maybe we want to switch those around.

**Comment by anjakefala** [comment]
> @ defop function names were preventing me from writing to an AIPL column with the same name

This is a fun bug!

**Comment by saulpw** [comment]
Ah, yes, we do want to switch those around.  I always think the ChainMap list is in reverse order.

**Comment by saulpw** [comment]
The order should be correct now!
