### ISSUE TITLE
How to provide API token?

### ISSUE THREAD

**Issue by justinwiley** [saulpw/aipl#53]
Neat project!  This may be obvious or I missed it in the README but how do you provide the chat gpt API token? I don't see an argument or env bar or something similar.

**Comment by saulpw** [comment]
Hey @justinwiley!  It's just the same envvar that the openai library uses: `OPENAI_API_KEY` (and `OPENAI_API_ORG`).  I think the library should even give an error saying that it needs to be set if it's missing?  If not then we should add that.
